name: "Create PyPi Package and Docker Image"

on:
  push:
    branches:
      - 'ci_dev'
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_version:
        description: The version that you would like to create a release for. This does not yet work
        required: true
        default: "v1.2.3"
      trigger_docker_latest:
        required: true
        default: "no"
      trigger_docker_release:
        required: true
        default: "no"
      trigger_pypi_dev:
        description: "Should we trigger the pypi-dev upload action? This will create a fake version number for upload."
        required: true
        default: "no"
      trigger_pypi_prod:
        required: true
        default: "no"

jobs:
  pypi-dev:
    name: Build a PyPi Package if this is a commit to the ci_dev branch
    runs-on: [ "self-hosted", "build_host" ]

    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/ci_dev')) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_pypi_dev == 'yes')

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Obtain current commit hash
      id: vars
      shell: bash
      run: |
        echo "::set-output name=commit::$(git rev-parse --short HEAD)"
        echo "::set-output name=commitint::$(git rev-parse HEAD | tr -d -c 0-9)"

    - name: Set dummy version number in setup.py for publishing unique version
      shell: bash
      run: |
        sed -i -E s/'version="(.+)",'/'version="0.0.'${{ steps.vars.outputs.commitint }}'"',/g setup.py

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution package to Test PyPI
      uses: ngardiner/gh-action-pypi-publish-proxy@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip_existing: true
        repository_url: https://test.pypi.org/legacy/

  pypi:
    name: Build a PyPi Package if this is a tagged release commit
    runs-on: [ "self-hosted", "build_host" ]

    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_pypi_prod == 'yes')

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution package to Test PyPI
      uses: ngardiner/gh-action-pypi-publish-proxy@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip_existing: true
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution package to Production PyPI
      uses: ngardiner/gh-action-pypi-publish-proxy@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  docker-latest:
    name: Create docker-latest Docker Image from current head
    runs-on: [ "self-hosted", "build_host" ]

    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_docker_latest == 'yes')

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        driver-opts: |
          env.http_proxy=http://192.0.2.1:3128
          env.https_proxy=http://192.0.2.1:3128

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: contrib/docker
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        push: true
        tags: twcmanager/twcmanager:latest
        build-args: |
          http_proxy=http://192.0.2.1:3128
          https_proxy=http://192.0.2.1:3128

  docker-release:
    name: Create docker-release Docker Image for release version
    runs-on: [ "self-hosted", "build_host" ]

    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_docker_release == 'yes')

    steps:

    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        driver-opts: |
          env.http_proxy=http://192.0.2.1:3128
          env.https_proxy=http://192.0.2.1:3128

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: contrib/docker
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        push: true
        tags: twcmanager/twcmanager:${{ steps.branch_name.outputs.SOURCE_TAG }}
        build-args: |
          http_proxy=http://192.0.2.1:3128
          https_proxy=http://192.0.2.1:3128
